version: "3"

services:
  postgres_locksmith:
    image: "postgres:latest"
    ports:
      - "5431:5432"
    env_file:
      - ".env-dev"
    volumes:
      - ./dentitydb_vol/:/var/lib/postgresql/data