version: "3"

services:
  postgres_locksmith:
    image: "postgres:latest"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=identity_db
    volumes:
      - ./identitydb_vol/:/var/lib/postgresql/data

